set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER clang-cl)
set(CMAKE_CXX_COMPILER clang-cl)
set(CMAKE_RC_COMPILER llvm-rc)
set(CMAKE_C_COMPILER_TARGET x86_64-pc-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-windows-msvc)
set(XWIN_DIR "$ENV{HOME}/.cache/xwin/splat" CACHE PATH "xwin splat directory")
set(CMAKE_C_FLAGS_INIT "-vctoolsdir ${XWIN_DIR}/crt -winsdkdir ${XWIN_DIR}/sdk")
set(CMAKE_CXX_FLAGS_INIT "-vctoolsdir ${XWIN_DIR}/crt -winsdkdir ${XWIN_DIR}/sdk")
set(CMAKE_C_FLAGS_DEBUG "")
set(CMAKE_C_FLAGS_RELEASE "")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "")
set(CMAKE_C_FLAGS_MINSIZEREL "")
set(CMAKE_CXX_FLAGS_DEBUG "")
set(CMAKE_CXX_FLAGS_RELEASE "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "")
set(CMAKE_CXX_FLAGS_MINSIZEREL "")
set(CMAKE_EXE_LINKER_FLAGS_INIT "/libpath:${XWIN_DIR}/sdk/lib/um/x86_64 /libpath:${XWIN_DIR}/sdk/lib/ucrt/x86_64 /libpath:${XWIN_DIR}/crt/lib/x86_64")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "/libpath:${XWIN_DIR}/sdk/lib/um/x86_64 /libpath:${XWIN_DIR}/sdk/lib/ucrt/x86_64 /libpath:${XWIN_DIR}/crt/lib/x86_64")
